### ISSUE TITLE
from_year and to_year

### ISSUE THREAD

**Issue by joerirogelj** [Rlamboll/EmissionsTradeAnalysis#1]
Is (from_year.Reporter == country) correct here?
Shouldn't it be (to_year.Partner == country)?

imports_to = to_year[(to_year["Trade Flow"] == "Import") & (to_year.Commodity == commodity) & (from_year.Reporter == country)]
exports_to = to_year[(to_year["Trade Flow"] == "Export") & (to_year.Commodity == commodity) & (from_year.Reporter == country)]

**Comment by Rlamboll** [comment]
It should be to_year.Reporter==country in both cases. Bug now fixed.
